services:
  - type: web
    name: reg-user
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        sync: false
      - key: AIRTABLE_TABLE_NAME_EMP
        sync: false
      - key: AIRTABLE_TABLE_NAME_LOG
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false